### ISSUE TITLE
Redirect to HTTPS for all HTTP verbs

### ISSUE THREAD

**Issue by ghost** [gregjhogan/redirect-http-to-https-site-extension#5] opened 2017-05-07 15:03 UTC
Hi,

I tried using your extension for my Azure web service (which is actually a ReST API). It works fine for GET requests, but fails for any other HTTP verbs, like POST, DELETE etc. The app service starts treating them as GET requests only when I try to issue POST request with postman on the http:// endpoint.

I have even raised a question about this on stackoverflow here : https://github.com/gregjhogan/redirect-http-to-https-site-extension/issues

Looking forward for your reply! :)

**Comment by AranVinkItility** [comment] 2017-05-16 14:15
Hi,

I was testing the same thing, and it works for HTTP POST in my case.

I'm using postman as well, but postman's default is to follow redirects. To work around this you need to enable the  'interceptor' and tick the 'Automatically follow redirects' button in the config screen.
Hope this helps :)

**Comment by ghost** [comment] 2017-05-16 15:27
@AranVinkItility , I'm not even sure I'm getting a proper redirect response code in the response for the POST call to http endpoint. I'll try again though, let's see.

**Comment by AranVinkItility** [comment] 2017-05-17 07:18
Using curl gives me a nice 301 redirect:
```
$ curl -s -o /dev/null -w "%{http_code}" http://yoururl
301
```

**Comment by gregjhogan** [comment] 2017-10-22 17:26
You want to change your POST request to specify https://.  It sounds like the issue is that clients often always perform a GET on redirect (no matter what the original method was).  Since it is already configured to redirect on all methods I am closing this.

**Closed as completed by gregjhogan** 2017-10-22 17:26 UTC
